### PR TITLE
time displaying on table and day column added

### PR DESCRIPTION
**Pull request by jboretsky**

### CODE REVIEW

**Comment by kradical** [comment]
Hey Jonah! I just did almost the same thing but also made it so that it combines adjacent bookings into 1 displayed booking, maybe close this pull request and take a look at what I did? Sorry :s.

**Comment by kryogenic** [comment]
let me know what you guys wanna do about this one ^_^

**Comment by kradical** [comment]
well whatever works for you guys, i can merge what jonahs done and make another pull request in a bit!

**Comment by jboretsky** [comment]
no probs it didn't take too long! if theres anything you can use from what i did just take it :)

**Pull request closed without merging**
